server:
  port: 8085

streams:
  commandTopic: "hello.demo.command"
  stateTopic: "hello.demo.customerstate"
  stateDir: "target/state"
  bootstrapServers: "localhost:9092"
  schemaRegistryUrl: "http://localhost:8081"
